feat : workflow 수정

diff --git a/.github/workflows/portfolio_ci.yml b/.github/workflows/portfolio_ci.yml
--- a/.github/workflows/portfolio_ci.yml
+++ b/.github/workflows/portfolio_ci.yml
@@ -32,11 +32,17 @@ jobs:
           yarn install --immutable 2> >(tee log_${{ github.run_id }}.txt) ; \
           test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }
 
+      - name: Core Build
+        id: core_build
+        run: |
+          yarn core build 2> >(tee test_log) ; \
+          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn core build failed." ; exit 1; }
+
       - name: Run Build
         id: run_build
         run: |
           yarn portfolio build 2> >(tee test_log) ; \
-          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn install failed." ; exit 1; }
+          test ${PIPESTATUS[0]} -eq 0 || { echo "yarn portfolio build failed." ; exit 1; }
 
       - name: Upload Log File
         if: failure()
